version: '2'
services:
    phpfpm:
        image: php:5.6.24-fpm
        volumes:
            - "./www.bbc.com:/var/www/html/www.bbc.com"
            - ./parser.php:/var/www/html/parser.php
 
